# Generated by Django 5.2 on 2025-04-17 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
